#lang racket
(require db)

(define PATH (current-directory-for-user)) ;can be set manually

(define (init-db! home)
  (define db (sqlite3-connect #:database home #:mode 'create))
  (unless (table-exists? db "users")
    (query-exec db "CREATE TABLE users (name TEXT PRIMARY KEY, password BLOB)"))
  (unless (table-exists? db "clubs")
    (query-exec db "CREATE TABLE clubs (name TEXT PRIMARY KEY, score INTEGER)"))
  (unless (table-exists? db "changinglogs")
    (query-exec db "CREATE TABLE changinglogs (id INTEGER PRIMARY KEY AUTOINCREMENT, club TEXT, comment TEXT, result INTEGER, logtime TIMESTAMP default (datetime('now', '+8 hour')))"))
  (unless (table-exists? db "user2club")
    (query-exec db "CREATE TABLE user2club (user TEXT, club TEXT, PRIMARY KEY (user, club))"))
  db)
(define db (init-db! (build-path PATH "database.sqlite")))

;(struct user (name password)) and password is hashed
;(struct user2club (user club))
(define (user-get name club)
  (cond
    ((and (equal? club "") (equal? name "")) (let ((users-list (query-list db "SELECT name FROM users ORDER BY name"))) (cons users-list (map (lambda (user) (string-join (user-club user) ",")) users-list))))
    ((equal? club "") (let ((res (user-club name))) (cons (make-list (length res) name) res)))
    ((equal? name "") (let ((user-list (club-user club))) (cons (make-list (length user-list) club) user-list)))
    (else (user-get name ""))))
(define (user-password name)
  (query-maybe-value db "SELECT password FROM users WHERE name = ?" name))
(define (user-insert! name clubs password);get a list of clubs
  (query-exec db "INSERT INTO users VALUES (?, ?)" name password)
  (map (lambda (c) (query-exec db "INSERT INTO user2club VALUES (?, ?)" name c)) clubs))
(define (user-rename! name newname)
  (query-exec db "UPDATE users SET name=? WHERE name=?" newname name))
(define (user-repassword! name password)
  (query-exec db "UPDATE users SET password=? WHERE name=?" password name))
(define (user-delete! name)
  (query-exec db "DELETE FROM users WHERE name=?" name)
  (query-exec db "DELETE FROM user2club WHERE user=?" name))
(define (user-rm-club! name club)
  (query-exec db "DELETE FROM user2club WHERE name=? AND club=?" name club))
(define (user-add-club! name club)
  (query-exec db "INSERT INTO user2club VALUES (?, ?)" name club))

(define (user-club name)
  (query-list db "SELECT club FROM user2club WHERE user = ? ORDER BY club" name))
(define (club-user name)
  (query-list db "SELECT user FROM user2club WHERE club = ? ORDER BY user" name))


;(struct club (name score))
(define (club-score name)
  (query-maybe-value db "SELECT score FROM clubs WHERE name = ?" name))
(define (club-rescore! name score)
  (query-exec db "UPDATE clubs SET score=? WHERE name=?" score name))
(define (club-insert! name score)
  (query-exec db "INSERT INTO clubs VALUES (?, ?)" name score))
(define (club-all) (cons (query-list db "SELECT name FROM clubs ORDER BY score, name DESC")
                         (query-list db "SELECT score FROM clubs ORDER BY score, name DESC")))

(define (club-rename! name newname)
  (query-exec db "UPDATE clubs SET name=? WHERE name=?" newname name)
  (query-exec db "UPDATE user2club SET club=? WHERE club=?"newname name))
(define (club-delete! name)
  (query-exec db "DELETE FROM clubs WHERE name=?" name)
  (query-exec db "DELETE FROM user2club WHERE club=?" name))

;(struct log (id club comment result logtime))
(define (log-*-byclub club)
  (if (equal? club "")
      (list (query-list db "SELECT club FROM changinglogs ORDER BY logtime DESC")
            (query-list db "SELECT comment FROM changinglogs ORDER BY logtime DESC")
            (query-list db "SELECT result FROM changinglogs ORDER BY logtime DESC")
            (query-list db "SELECT logtime FROM changinglogs ORDER BY logtime DESC"))
      (list (query-list db "SELECT club FROM changinglogs WHERE club=? ORDER BY logtime DESC" club)
            (query-list db "SELECT comment FROM changinglogs WHERE club=? ORDER BY logtime DESC" club)
            (query-list db "SELECT result FROM changinglogs WHERE club=? ORDER BY logtime DESC" club)
            (query-list db "SELECT logtime FROM changinglogs WHERE club=? ORDER BY logtime DESC" club))))
(define (log-insert! club comment result)
  (query-exec db "INSERT INTO changinglogs (club, comment, result) VALUES (?, ?, ?)" club comment result)
  (club-rescore! club result))
(define (log-change! club comment change)
  (log-insert! club (string-append (number->string change) comment) (+ (club-score club) change)))
(provide (all-defined-out))